### ISSUE TITLE
Can't change stop

### ISSUE THREAD

**Issue by amomat** [CatoAntonsen/MMM-Ruter#4]
Hi

Thanks for uploading this. Looks really nice. Tried adding it on my MM but when I enter my tram stop (Furulund "3012530") it just sais loading. Tried other stopId as well but doesnt load. When I replace "3012530" with your example stop "3010972" it comes up just fine. Have no idea what I'm doing wrong. Could you please take a look at it?

**Comment by amomat** [comment]
Took out a log that I hope can help:

0|mm       |     at process._tickCallback (internal/process/next_tick.js:98:9)
0|mm       | SyntaxError: Unexpected end of JSON input
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ruter/node_helper.js:98:22)
0|mm       |     at emitNone (events.js:91:20)
0|mm       |     at IncomingMessage.emit (events.js:185:7)
0|mm       |     at endReadableNT (_stream_readable.js:974:12)
0|mm       |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
0|mm       |     at process._tickCallback (internal/process/next_tick.js:98:9)
0|mm       | SyntaxError: Unexpected token < in JSON at position 0
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ruter/node_helper.js:98:22)
0|mm       |     at emitNone (events.js:91:20)
0|mm       |     at IncomingMessage.emit (events.js:185:7)
0|mm       |     at endReadableNT (_stream_readable.js:974:12)
0|mm       |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
0|mm       |     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by CatoAntonsen** [comment]
Your stop works for me, but remember to remove/update platforms. If you forget to remove "my" platforms (1 and 2), then what you say will happen.

Take a look at showPlatform=true to find what platforms you can use.

**Comment by amomat** [comment]
Thanks. Works now.
