### ISSUE TITLE
More than instance of the module

### ISSUE THREAD

**Issue by FierceNorse** [CatoAntonsen/MMM-Ruter#5]
Hi,

Is it possible to show more than one instance of this module at the same time? 
I tried to configure two, with different stop-IDs, but both module instances show the same line/route-information. 
Also; are there limitations in the API from Ruter that limits for how many minutes/hours ahead it shows the info? -> I have inputted a stop ID with only 1 or 2 departures pr. hour, and it only shows for the next 2 hours (it seems). When the last train has departed, the module is empty (instead of showing the first departures the next morning).

På forhånd takk :)

**Comment by CatoAntonsen** [comment]
Hi,

At the moment you can not add more than one instance of this module. It's on my TODO-list, but I've been busy with other stuff. You know you **can** add more than one stop in one instance, right...? 

I am not aware of how long time ahead they will return results for. I've asked them this on their Facebook page.

**Comment by FierceNorse** [comment]
Hi, 

I wasn't aware that more than 1 stop could be added to the same module. 

How is this done?

**Comment by CatoAntonsen** [comment]
Hi, I've updated the example in README.md to show how to add multiple stops.

I finally received an answere from Ruter. They only return the trips for the next couple of hours, without specifying exactly how many hours. Will look into maybe query for trips forward in time if no results are returned.

**Comment by CatoAntonsen** [comment]
@xy86 I've merged @Mixopteryx's PR so you should now be able to add multiple instances of this module.

**Comment by CatoAntonsen** [comment]
@xy86 I created issue #7 for the issue about journeys in the morning not showing. Can you go there and update status?

**Comment by alistairspalding** [comment]
@CatoAntonsen 

> Hi, I've updated the example in README.md to show how to add multiple stops.

I can't see that this has been done and I can't manage to work it out from @Mixopteryx code. Could you update the README.md with this info when you get the chance.

**Comment by Mixopteryx** [comment]
Copied from readme.md:

Stop option | Comment
---|---|--- stopId | Id of stop
platformFilter | The names of the platforms you want to see timeToThere |
How long time in minutes does it take for you to get to this stop? It's no
point showing journeys that till go in 1 minute if it takes you 5 minutes
to get there...

Example:

stops: [
{
stopId: "3010972",
platforms: [ "1", "2" ],
timeToThere: 0
},
{
stopId: "3010910",
timeToThere: 15
},
]


man. 17. apr. 2017 kl. 22.05 skrev alistairspalding <
notifications@github.com>:

**Comment by alistairspalding** [comment]
@CatoAntonsen @Mixopteryx My mistake. I confused instances with stops. 

I'm currently running two instances successfully. Many thanks.
