### ISSUE TITLE
Module won't load when I change station

### ISSUE THREAD

**Issue by agskaali** [CatoAntonsen/MMM-Ruter#8]
Whenever I try to change the stopId the module won't load any results.

My stopId is 2190050

Am I doing something wrong?

**Comment by CatoAntonsen** [comment]
Works for me. Can you please paste your module config here?

**Comment by agskaali** [comment]
I have only done changes to the default config.js:

{
			module: 'MMM-Ruter',
			header: 'Ruter',
			position: 'top_right',
			config: {
				showPlatform: false, 
				maxItems: 6,
				stops: [
					{
						stopId: "2190050",
						platforms: [ "1", "2" ],
						timeToThere: 0
					}
				]
			}
		},

**Comment by CatoAntonsen** [comment]
Your config for `platforms` is not valid. There are no platform named "1" or "2".

I've updated the README to hopefully make debugging this easier. Take a look at the Stops-section.
